app:
  jwks: classpath:jwks.json
spring:
  application:
    name: mockpass-spring-boot-example
  security:
    oauth2:
      client:
        registration:
          mockpass:
            client-id: mockpass-spring-boot-example
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            scope:
            - openid
        provider:
          mockpass:
            issuer-uri: http://localhost:5156/singpass/v2